# Generated by Django 3.0.5 on 2020-04-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='client',
            name='age',
        ),
    ]
