# Generated by Django 3.0.5 on 2020-04-14 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200414_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.User'),
        ),
    ]
