# Generated by Django 3.0.5 on 2020-04-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_client_trainer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
