# Generated by Django 3.0.5 on 2020-04-15 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_delete_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['last_name']},
        ),
        migrations.CreateModel(
            name='LoggedWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_logged_workouts', to='clientmanager.Client')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logged_workouts', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logged_instances', to='workouts.CreatedWorkout')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
