# Generated by Django 3.0.5 on 2020-04-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientmanager', '0002_auto_20200415_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedworkout',
            name='date',
            field=models.DateField(),
        ),
    ]
