# Generated by Django 3.0.5 on 2020-04-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='movement_type',
            field=models.CharField(blank=True, choices=[('Con', 'Concentric'), ('Ecc', 'Eccentric'), ('Iso', 'Isometric'), ('Non', 'Non-Specific')], max_length=3),
        ),
    ]
