# Generated by Django 3.0.5 on 2020-04-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_database', '0002_exercise_movement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='variation',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='movement_type',
            field=models.CharField(blank=True, choices=[('UPH', 'Upper Body Push'), ('UPL', 'Upper Body Pull'), ('LPH', 'Lower Body Push'), ('LPL', 'Lower Body Pull'), ('COR', 'Core'), ('COM', 'Combination')], max_length=3),
        ),
    ]
