# Generated by Django 3.0.5 on 2020-04-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20200411_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdworkout',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
