# Generated by Django 3.0.5 on 2020-04-12 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_auto_20200411_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutblock',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='workouts.CreatedWorkout'),
        ),
    ]
