# Generated by Django 3.0.5 on 2020-04-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_auto_20200411_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='reps',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
