# Generated by Django 3.0.5 on 2020-04-13 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0006_auto_20200411_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdworkout',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_workouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
