# Generated by Django 3.0.5 on 2020-04-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
